version: '3.9'

networks:
    x-private:
        external: true
    x-public:
        external: true


services:
  excel-service:
    build: .
    container_name: excel-service
    ports:
      - 9090:9090 
    networks:
      - x-public
      - x-private
    restart: on-failure