- hosts: all
  roles:
    - service-deploy
  vars:
    service_network_name: x-private
    service_network_is_external: true
    service_network_alias: parser
    service_environments:
      PORT: '9090'
      DB_HOST: "{{ lookup('env', 'DB_HOST') }}"
      DB_PORT: "{{ lookup('env', 'DB_PORT') }}"
      DB_USERNAME: "{{ lookup('env', 'DB_USERNAME') }}"
      DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
      DB_DATABASE: "{{ lookup('env', 'DB_DATABASE') }}"
      XCLOUD_DIRECTUS_S3_HOST: "{{ lookup('env', 'XCLOUD_DIRECTUS_S3_HOST') }}"
      XCLOUD_DIRECTUS_S3_KEY: "{{ lookup('env', 'XCLOUD_DIRECTUS_S3_KEY') }}"
      XCLOUD_DIRECTUS_S3_SECRET: "{{ lookup('env', 'XCLOUD_DIRECTUS_S3_SECRET') }}"
      XCLOUD_DIRECTUS_S3_BUCKET: "{{ lookup('env', 'XCLOUD_DIRECTUS_S3_BUCKET') }}"