- hosts: all
  roles:
    - service-deploy
  vars:
    service_network_name: x-private
    service_network_is_external: true
    service_network_alias: parser
    service_environments:
      PORT: '9090'
      DB_HOST: "{{ lookup('env', 'DB_HOST') }}"
      DB_PORT: "{{ lookup('env', 'DB_PORT') }}"
      DB_USERNAME: "{{ lookup('env', 'DB_USERNAME') }}"
      DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
      DB_DATABASE: "{{ lookup('env', 'DB_DATABASE') }}"
      XCLOUD_DIRECTUS_S3_HOST: '10.90.70.33:9000'
      XCLOUD_DIRECTUS_S3_KEY: 'c57f2f45-fbbb-4edc-a0d1-4fbe13178001'
      XCLOUD_DIRECTUS_S3_SECRET: '4fbe13178001'
      XCLOUD_DIRECTUS_S3_BUCKET: 'xmarket'